l_name_number = {"s": 0,
                 "p": 1,
                 "d": 2,
                 "f": 3,
                 "g": 4,
                 "h": 5,
                 "i": 6,
                 "j": 7,
                 "k": 8,
                 "l": 9}

l_number_name = {0: "s",
                 1: "p",
                 2: "d",
                 3: "f",
                 4: "g",
                 5: "h",
                 6: "i",
                 7: "j",
                 8: "k",
                 9: "l"}

atomic_number = {"Actinium"      : 89,
                 "Aluminum"      : 13,
                 "Americium"     : 95,
                 "Antimony"      : 51,
                 "Argon"         : 18,
                 "Arsenic"       : 33,
                 "Astatine"      : 85,
                 "Barium"        : 56,
                 "Berkelium"     : 97,
                 "Beryllium"     : 4,
                 "Bismuth"       : 83,
                 "Bohrium"       : 107,
                 "Boron"         : 5,
                 "Bromine"       : 35,
                 "Cadmium"       : 48,
                 "Calcium"       : 20,
                 "Californium"   : 98,
                 "Carbon"        : 6,
                 "Cerium"        : 58,
                 "Cesium"        : 55,
                 "Chlorine"      : 17,
                 "Chromium"      : 24,
                 "Cobalt"        : 27,
                 "Copper"        : 29,
                 "Curium"        : 96,
                 "Darmstadtium"  : 110,
                 "Dubnium"       : 105,
                 "Dysprosium"    : 66,
                 "Einsteinium"   : 99,
                 "Erbium"        : 68,
                 "Europium"      : 63,
                 "Fermium"       : 100,
                 "Fluorine"      : 9,
                 "Francium"      : 87,
                 "Gadolinium"    : 64,
                 "Gallium"       : 31,
                 "Germanium"     : 32,
                 "Gold"          : 79,
                 "Hafnium"       : 72,
                 "Hassium"       : 108,
                 "Helium"        : 2,
                 "Holmium"       : 67,
                 "Hydrogen"      : 1,
                 "Indium"        : 49,
                 "Iodine"        : 53,
                 "Iridium"       : 77,
                 "Iron"          : 26,
                 "Krypton"       : 36,
                 "Lanthanum"     : 57,
                 "Lawrencium"    : 103,
                 "Lead"          : 82,
                 "Lithium"       : 3,
                 "Lutetium"      : 71,
                 "Magnesium"     : 12,
                 "Manganese"     : 25,
                 "Meitnerium"    : 109,
                 "Mendelevium"   : 101,
                 "Mercury"       : 80,
                 "Molybdenum"    : 42,
                 "Neodymium"     : 60,
                 "Neon"          : 10,
                 "Neptunium"     : 93,
                 "Nickel"        : 28,
                 "Niobium"       : 41,
                 "Nitrogen"      : 7,
                 "Nobelium"      : 102,
                 "Osmium"        : 76,
                 "Oxygen"        : 8,
                 "Palladium"     : 46,
                 "Phosphorus"    : 15,
                 "Platinum"      : 78,
                 "Plutonium"     : 94,
                 "Polonium"      : 84,
                 "Potassium"     : 19,
                 "Praseodymium"  : 59,
                 "Promethium"    : 61,
                 "Protactinium"  : 91,
                 "Radium"        : 88,
                 "Radon"         : 86,
                 "Rhenium"       : 75,
                 "Rhodium"       : 45,
                 "Rubidium"      : 37,
                 "Ruthenium"     : 44,
                 "Rutherfordium" : 104,
                 "Samarium"      : 62,
                 "Scandium"      : 21,
                 "Seaborgium"    : 106,
                 "Selenium"      : 34,
                 "Silicon"       : 14,
                 "Silver"        : 47,
                 "Sodium"        : 11,
                 "Strontium"     : 38,
                 "Sulfur"        : 16,
                 "Tantalum"      : 73,
                 "Technetium"    : 43,
                 "Tellurium"     : 52,
                 "Terbium"       : 65,
                 "Thallium"      : 81,
                 "Thorium"       : 90,
                 "Thulium"       : 69,
                 "Tin"           : 50,
                 "Titanium"      : 22,
                 "Tungsten"      : 74,
                 "Ununbium"      : 112,
                 "Ununhexium"    : 116,
                 "Ununoctium"    : 118,
                 "Ununpentium"   : 115,
                 "Ununquadium"   : 114,
                 "Ununseptium"   : 117,
                 "Ununtrium"     : 113,
                 "Ununium"       : 111,
                 "Uranium"       : 92,
                 "Vanadium"      : 23,
                 "Xenon"         : 54,
                 "Ytterbium"     : 70,
                 "Yttrium"       : 39,
                 "Zinc"          : 30,
                 "Zirconium"     : 40}
